### ISSUE TITLE
Is there a way to see the curve over 24h?

### ISSUE THREAD

**Issue by coaxial** [haberda/update_lights#11]
I'm really struggling wrapping my head around the algorithm for some reason. I think visualizing the curve like in the README but for my particular config would help. Is there a way to see it?

What I'd like to achieve: lights gradually warm up and dim down as we approach sunset. After sunset, the lights are around 20% brightness until midnight, where they switch to the warmest temperature and lowest brightness (say 5%), until 1h before sunrise. After that point, they gradually warm up and become brighter until sunrise where they switch to max brightness and cold temp until sunset again.

So this is what I have:

```
lights_temp:
  module: update_lights
  class: update_lights
  start_time: sunset
  end_time: sunrise
  start_index: 00:00:00
  end_index: sunrise - 01:00:00
  color_temp_max: 4000
  color_temp_min: 2000
  brightness_unit: percent
  max_brightness_level: 100
  min_brightness_level: 5
  brightness_threshold: 5
  watch_light_state: true
  run_every: 60
```

But that doesn't seem to work. The lights are very dim at some point in the afternoon way before sunset when they should be cold and bright. What am I doing wrong?
