### ISSUE TITLE
I... I am too dumb.

### ISSUE THREAD

**Issue by christianreiss** [haberda/update_lights#13]
So I have been playing with this for two days now. It looks like it can do what I want, which basically is to have 

- Start increasing brightness and color in the morning from 1 hour (or so) before sunrise and be done 2 hours or so after sunrise.
- Start decreasing brightness and color in the evening from 2 hours or so before sunrise an be in full effect 2 hours after (or so).

I have been reading the documentation but honestly, that is beyond me. And I am running a 400-or-so automations HA setup with 28 integrations. But this beats me. 

I have been whacking at the settings in an orderly fashion at first, randomly bashing later.

```
main_periodic_lights:
  module: update_lights
  class: update_lights
  run_every: 180
  event_subscription: main_update_lights
  entities:
    - light.mi_esstischlampe
    - light.mi_licht_badezimmer
    - light.mi_licht_theodor
    - light.mi_licht_wohnzimmer_tv
    - light.licht_kuche
    - light.licht_johann
    - light.licht_schlafzimmer_4
    - light.licht_buro_3
  brightness_threshold: 25
  color_temp_max: 4100
  color_temp_min: 3000
# color_temp_unit: 'kelvin'
  max_brightness_level: 100
  min_brightness_level: 35
  brightness_unit: 'percent'
  sleep_entity:
    - input_boolean.just_woke_up,off
  disable_entity:
    - input_boolean.watching_tv,on
# red_hour: '21:00:00'
  start_time: sunset - 04:00:00
  end_time: sunrise + 01:00:00
  start_index: sunrise - 02:00:00
  end_index: sunset
  transition: 5
  keep_lights_on: False
  stop_lights_off: True
  watch_light_state: True
  sensor_log: sensor.main_lights
```
I have been playing with start_time, end_time, start_index etc. Even after reading the documentation 10 or so time I still don't know what they do. Sorry :)

Could someone pleas help me and roughly tell me what goes where? 
And a "lamens section" in the documentation would not go amiss. 

Cheers!
-Chris.
