### ISSUE TITLE
Lights get turned back on after they should be turned off

### ISSUE THREAD

**Issue by Kirbo** [haberda/update_lights#7]
I have a setup such as `automation.yaml`:
```yaml
- alias: Hallway lights on when motion detected or front door is open
  id: hallway_turn_on_the_lights_by_movement_or_door
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.frontdoor_motion
    - binary_sensor.eve_door_etuovi
    to: 'on'
  action:
  - service: light.turn_on
    entity_id:
    - light.etuovi
    - light.eteinen


- alias: Hallway lights off when motion detected or front door is open
  id: hallway_turn_off_the_lights_by_movement_or_door
  trigger:
  - platform: state
    entity_id: binary_sensor.frontdoor_motion
    to: 'off'
    for: 00:00:45
  - platform: state
    entity_id: binary_sensor.eve_door_etuovi
    to: 'off'
    for: 00:00:45
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: binary_sensor.eve_door_etuovi
      state: 'off'
    - condition: state
      entity_id: binary_sensor.frontdoor_motion
      state: 'off'
  action:
  - service: light.turn_off
    data:
      entity_id:
      - light.etuovi
      - light.eteinen
      transition: 15


- alias: Lights on when motion in bathroom
  id: lights_on_when_motion_in_bathroom
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.bathroom_motion
    to: 'on'
  action:
  - service: light.turn_on
    entity_id:
    - light.kylpyhuone_ledi


    
- alias: Lights off when no motion in bathroom and door is open
  id: lights_off_when_no_motion_in_bathroom_and_door_is_open
  trigger:
  - platform: state
    entity_id: binary_sensor.bathroom_motion
    to: 'off'
    for: 00:00:45
  condition:
    - condition: state
      entity_id: binary_sensor.eve_door_kylpyhuone
      state: 'on'
  action:
  - service: light.turn_off
    data:
      entity_id:
      - light.kylpyhuone_ledi
      transition: 15


- alias: Lights off when no motion in bathroom and door is closed
  id: lights_off_when_no_motion_in_bathroom_and_door_is_closed
  trigger:
  - platform: state
    entity_id: binary_sensor.bathroom_motion
    to: 'off'
    for: 00:14:45
  condition:
    - condition: state
      entity_id: binary_sensor.eve_door_kylpyhuone
      state: 'off'
  action:
  - service: light.turn_off
    data:
      entity_id:
      - light.kylpyhuone_ledi
      transition: 15



- alias: Lights on when motion in wc hallway
  id: lights_on_when_motion_in_wc_hallway
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.hallway_motion
    to: 'on'
  action:
  - service: light.turn_on
    entity_id:
    - light.wc_eteinen


- alias: Lights off when motion in wc hallway
  id: lights_off_when_motion_in_wc_hallway
  trigger:
  - platform: state
    entity_id: binary_sensor.hallway_motion
    to: 'off'
    for: 00:00:45
  action:
  - service: light.turn_off
    data:
      entity_id:
      - light.wc_eteinen
      transition: 15
```

and `apps.yaml`:
```yaml
motion_lights:
  module: update_lights
  class: update_lights
  run_every: 0
  entities:
    - light.kylpyhuone_ledi
    - light.etuovi
    - light.eteinen
    - light.wc_eteinen
  brightness_threshold: 0
  color_temp_max: 250
  color_temp_min: 500
  color_temp_unit: 'mired'
  max_brightness_level: 100
  min_brightness_level: 10
  brightness_unit: 'percent'
  red_hour: '01:00:00'
  start_time: sunset - 3:00:00
  end_time: sunrise + 2:00:00
  start_index: '19:00:00'
  end_index: '06:00:00'
  keep_lights_on: false
  start_lights_on: false
  stop_lights_off: false
  watch_light_state: true
  sensor_log: sensor.motion_lights
```

If I remove the `motion_lights` app, my automations work as intended:
They turn on when there is motion (and/or door is opened) and turned off when there has not been motion detected in given time (and door is open/closed).
But once I add this `motion_lights`, my lights get turned back on after the 15 second transition.
Any idea what would cause this? I'm suspecting that `run_every` does not respect the value of `0`. I might be completely wrong as well, as I have tried other values as well, such as `3600`, `300`, etc. but still the lights get turned back on right after the transition has finished or right at the end of the transition. Even this is not consistent, it keeps turning the lights back to the value they were when the light turned on (thus ignoring the transition and turning the light off).

One very probable cause of this behaviour is my configuration. As I'm not 100% sure whether I've configured it properly, I don't know.

arch | aarch64
-- | --
chassis | embedded
dev | false
docker | true
docker_version | 19.03.11
hassio | true
host_os | HassOS 4.15
installation_type | Home Assistant OS
os_name | Linux
os_version | 4.19.127-v8
python_version | 3.8.6
supervisor | 2020.11.0
timezone | Europe/Helsinki
version | 0.117.2
virtualenv | false

```
2020-11-04 23:04:33.172554 INFO AppDaemon: AppDaemon Version 4.0.5 starting
2020-11-04 23:04:33.173061 INFO AppDaemon: Python version is 3.8.5
```

Latest version of `update_lights`.

Please let me know if I could provide you some more information.

**Comment by haberda** [comment]
AppDaemon does not recognize lower case True and False as boolean variables. So when you have:
  keep_lights_on: false
that statement actually returns True because of python boolean logic.
Change all of your false to False; likewise with true to True and see if that fixes it. Alternatively, keep_lights_on is False by default so you can just delete it.

Home assistant has spoiled us by having checks for lower case boolean. I could include those checks in the code, but it would add an additional logic statement for each variable and the code is quite long as it is.

**Comment by Kirbo** [comment]
@haberda Thanks for quick reply! 🙂

I changed the config now as following, but still I get the same behaviour.
- Lights are on for 45 seconds after no motion is detected
- Lights begin their 15 second transition from current brightness to off
- Either during the transition OR after the lights have completely turned off, they turn back on at the very same brightness level they were before the transition

If I remove this `update_lights` configuration, the lights behave as they should (does not turn back on) and once I enable the configuration below, they start to misbehave.

Am I still missing something?

```yaml
motion_lights:
  module: update_lights
  class: update_lights
  run_every: False
  entities:
    - light.kylpyhuone_ledi
    - light.etuovi
    - light.eteinen
    - light.wc_eteinen
  brightness_threshold: 100
  color_temp_max: 250
  color_temp_min: 500
  color_temp_unit: 'mired'
  max_brightness_level: 100
  min_brightness_level: 10
  brightness_unit: 'percent'
  red_hour: '01:00:00'
  start_time: sunset - 3:00:00
  end_time: sunrise + 2:00:00
  start_index: '19:00:00'
  end_index: '06:00:00'
  keep_lights_on: False
  start_lights_on: False
  stop_lights_off: False
  watch_light_state: True
  sensor_log: sensor.motion_lights
```

```yaml
motion_lights:
  module: update_lights
  class: update_lights
  run_every: 0
  entities:
    - light.kylpyhuone_ledi
    - light.etuovi
    - light.eteinen
    - light.wc_eteinen
  brightness_threshold: 0
  color_temp_max: 250
  color_temp_min: 500
  color_temp_unit: 'mired'
  max_brightness_level: 100
  min_brightness_level: 10
  brightness_unit: 'percent'
  red_hour: '01:00:00'
  start_time: sunset - 3:00:00
  end_time: sunrise + 2:00:00
  start_index: '19:00:00'
  end_index: '06:00:00'
  keep_lights_on: False
  start_lights_on: False
  stop_lights_off: False
  watch_light_state: True
  sensor_log: sensor.motion_lights
```
